# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ main, dev ]
  pull_request: 

jobs:

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: System packages needed by build/tests
        run: |
          sudo apt-get update
          sudo apt-get install -y make git

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install local packages
        run: |
          pip install -v . ./xlnstorch

      - name: Lint with flake8
        run: |
          # Fail immediately on serious errors
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Style report (doesn't fail the build)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run pytest (on xlnstorch tests)
        run: |
          pytest test/xlnstorch

  docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python for docs
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: System packages needed by docs
        run: |
          sudo apt-get update
          sudo apt-get install -y make git

      - name: Install docs requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi

      - name: Install local packages
        run: |
          pip install . ./xlnstorch

      - name: Build docs with Sphinx
        run: |
          make -C docs html

      - name: Deploy docs to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh_pages